name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build and Test
      run: ./build.ps1
    - name: Publish NuGet Package
      if: |
        (github.event_name == 'create' && github.event.ref_type == 'tag') ||
        (github.event_name == 'push' && github.event.ref == 'refs/heads/preview')
      run: dotnet nuget push drop/**/*.nupkg --api-key $env:NUGET_KEY --source https://nuget.org
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
